---
all:
  children:
    zuul_nodes:
      children:
        jenkins_masters:
          hosts:
            jenkins-staging.phx.ovirt.org:
            jenkins.ovirt.org:
        source_hosts:
          hosts:
            zuul-staging.phx.ovirt.org:
            zuul01.phx.ovirt.org:


