---
all:
  vars:
    build_node_selector:
      type: "vm"
  children:
    base_images:
      hosts:
        jenkins-2-centos7:
          upstream_image: openshift/jenkins-2-centos7:v3.11
        jenkins-slave-base-centos7:
          upstream_image: openshift/jenkins-slave-base-centos7
        jenkins-caching-virt-agent-centos7:
          upstream_image:
            quay.io/pod_utils/jenkins-caching-virtualization-agent:master
    custom_images:
      hosts:
        stdci-jenkins-master:
          base_images:
            - jenkins-2-centos7
          image_source: container/jenkins-master-s2i
        stdci-loader-node:
          base_images:
            - jenkins-slave-base-centos7
          image_source: container/el7-loader-node
        stdci-integ-node-el7:
          base_images:
            - jenkins-caching-virt-agent-centos7
          image_source: container/el7-runner-node
