- name: 'PLAYBOOK'
  value: deploy_to_container
- name: 'INVENTORY'
  value: blank
- name: 'PB_ARGS'
  value: '-e build_node_selector={"type":"vm","zone":"ci"}'
- name: 'APISERVER'
  value: https://shift.ovirt.org:8443
- name: 'PROJECT'
  valueFrom:
    runtimeEnv: 'OPENSHIFT_PROJECT'
- name: 'TOKEN'
  valueFrom:
    secretKeyRef:
      name: 'openshift-deploy-serviceaccount'
      key: 'token'
- name: 'REPO_NAME'
  valueFrom:
    runtimeEnv: 'REPO_NAME'
- name: 'REPOMAN_SOURCES'
  valueFrom:
    runtimeEnv: 'REPOMAN_SOURCES'
